language: php
php:
  - 5.6
node_js: "7.2"

before_install:
  - nvm install 7.2
  - nvm use 7.2

install:
  - cd frontend && npm install
  - composer self-update
  - cd ../backend && composer install -n

before_script:
  - mysql -e 'create database `dev_heycommunity`;'
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate:refresh --seed -n
  # - ./vendor/bin/codecept build

script:
  #- ./vendor/bin/codecept run
  - cd ../frontend && npm run ionic:build
